language: php
php:
  - 5.6
cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: false

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  tag_name: "v0.1.$(git rev-list --no-merges --count HEAD master)-alpha"
  name: "v0.1.$(git rev-list --no-merges --count HEAD master)-alpha"
  file:
    - "gmx-web.zip"
    - "gmx-web-updates.zip"
  skip_cleanup: true
  on:
    tags: false
    branch: master
before_deploy: bash scripts/deploy.sh
script: composer install --no-dev