language: php
php:
  - 7.2.21
cache:
  directories:
    - $HOME/.composer/cache/files
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  tag_name: "v0.1.$(git rev-list --count HEAD)-alpha"
  script: bash scripts/deploy.sh
  name: "v0.1.$(git rev-list --count HEAD)-alpha"
  file: "gmx-web-updates.zip"
  skip_cleanup: true
  on:
    tags: false
    branch: master
script: composer install