language: php
php:
  - 7.2.21
cache:
  directories:
    - $HOME/.composer/cache/files
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  name: "v0.1.$(git rev-list --count HEAD)-alpha"
  file: "gmx-web-updates.zip"
  skip_cleanup: true
  on:
    branch: master
before_script: composer install
script: php manifest.php 0.1.$(git rev-list --count HEAD)-alpha